//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Client : object
    {
        
        private string AdresaField;
        
        private ServiceReference2.Auto[] AutomobileField;
        
        private string EmailField;
        
        private int IdField;
        
        private string JudetField;
        
        private string LocalitateField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private string TelefonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Auto[] Automobile
        {
            get
            {
                return this.AutomobileField;
            }
            set
            {
                this.AutomobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet
        {
            get
            {
                return this.JudetField;
            }
            set
            {
                this.JudetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate
        {
            get
            {
                return this.LocalitateField;
            }
            set
            {
                this.LocalitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Auto : object
    {
        
        private ServiceReference2.Client ClientField;
        
        private int ClientIdField;
        
        private ServiceReference2.Comanda[] ComenziField;
        
        private int IdField;
        
        private string NumarAutoField;
        
        private ServiceReference2.Sasiu SasiuField;
        
        private int SasiuIdField;
        
        private string SerieSasiuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Comanda[] Comenzi
        {
            get
            {
                return this.ComenziField;
            }
            set
            {
                this.ComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Sasiu Sasiu
        {
            get
            {
                return this.SasiuField;
            }
            set
            {
                this.SasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId
        {
            get
            {
                return this.SasiuIdField;
            }
            set
            {
                this.SasiuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Sasiu : object
    {
        
        private ServiceReference2.Auto[] AutomobileField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Auto[] Automobile
        {
            get
            {
                return this.AutomobileField;
            }
            set
            {
                this.AutomobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Comanda : object
    {
        
        private ServiceReference2.Auto AutoField;
        
        private int AutoIdField;
        
        private System.DateTime DataFinalizareField;
        
        private System.DateTime DataProgramareField;
        
        private System.DateTime DataSystemField;
        
        private string DescriereField;
        
        private ServiceReference2.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private int KmBordField;
        
        private ServiceReference2.StareComanda StareComandaField;
        
        private decimal ValoarePieseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Auto Auto
        {
            get
            {
                return this.AutoField;
            }
            set
            {
                this.AutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId
        {
            get
            {
                return this.AutoIdField;
            }
            set
            {
                this.AutoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizare
        {
            get
            {
                return this.DataFinalizareField;
            }
            set
            {
                this.DataFinalizareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare
        {
            get
            {
                return this.DataProgramareField;
            }
            set
            {
                this.DataProgramareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem
        {
            get
            {
                return this.DataSystemField;
            }
            set
            {
                this.DataSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord
        {
            get
            {
                return this.KmBordField;
            }
            set
            {
                this.KmBordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.StareComanda StareComanda
        {
            get
            {
                return this.StareComandaField;
            }
            set
            {
                this.StareComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese
        {
            get
            {
                return this.ValoarePieseField;
            }
            set
            {
                this.ValoarePieseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class DetaliuComanda : object
    {
        
        private ServiceReference2.Comanda ComandaField;
        
        private int ComandaIdField;
        
        private int IdField;
        
        private ServiceReference2.Imagine[] ImaginiField;
        
        private ServiceReference2.Material[] MaterialeField;
        
        private ServiceReference2.Mecanic[] MecaniciField;
        
        private ServiceReference2.Operatie[] OperatiiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Comanda Comanda
        {
            get
            {
                return this.ComandaField;
            }
            set
            {
                this.ComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId
        {
            get
            {
                return this.ComandaIdField;
            }
            set
            {
                this.ComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Imagine[] Imagini
        {
            get
            {
                return this.ImaginiField;
            }
            set
            {
                this.ImaginiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Material[] Materiale
        {
            get
            {
                return this.MaterialeField;
            }
            set
            {
                this.MaterialeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Mecanic[] Mecanici
        {
            get
            {
                return this.MecaniciField;
            }
            set
            {
                this.MecaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Operatie[] Operatii
        {
            get
            {
                return this.OperatiiField;
            }
            set
            {
                this.OperatiiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StareComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public enum StareComanda : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAsteptare = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executata = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refuzata = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Necunoscuta = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Imagine : object
    {
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private ServiceReference2.DetaliuComanda[] DetaliiComenziField;
        
        private byte[] FotoField;
        
        private int IdField;
        
        private string TitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Material : object
    {
        
        private decimal CantitateField;
        
        private System.DateTime DataAprovizionareField;
        
        private string DenumireField;
        
        private ServiceReference2.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private decimal PretField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate
        {
            get
            {
                return this.CantitateField;
            }
            set
            {
                this.CantitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare
        {
            get
            {
                return this.DataAprovizionareField;
            }
            set
            {
                this.DataAprovizionareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret
        {
            get
            {
                return this.PretField;
            }
            set
            {
                this.PretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Mecanic : object
    {
        
        private ServiceReference2.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Operatie : object
    {
        
        private string DenumireField;
        
        private ServiceReference2.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private decimal TimpExecutieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie
        {
            get
            {
                return this.TimpExecutieField;
            }
            set
            {
                this.TimpExecutieField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICarService")]
    public interface ICarService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomer", ReplyAction="http://tempuri.org/ICarService/FindCustomerResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Client> FindCustomerAsync(string nume, string prenume, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddCustomer", ReplyAction="http://tempuri.org/ICarService/AddCustomerResponse")]
        System.Threading.Tasks.Task AddCustomerAsync(ServiceReference2.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetAllCustomers", ReplyAction="http://tempuri.org/ICarService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Client[]> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddChassis", ReplyAction="http://tempuri.org/ICarService/AddChassisResponse")]
        System.Threading.Tasks.Task AddChassisAsync(ServiceReference2.Sasiu sasiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisByCode", ReplyAction="http://tempuri.org/ICarService/FindChassisByCodeResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Sasiu> FindChassisByCodeAsync(string chassisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddAuto", ReplyAction="http://tempuri.org/ICarService/AddAutoResponse")]
        System.Threading.Tasks.Task AddAutoAsync(ServiceReference2.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMaterial", ReplyAction="http://tempuri.org/ICarService/AddMaterialResponse")]
        System.Threading.Tasks.Task AddMaterialAsync(ServiceReference2.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrder", ReplyAction="http://tempuri.org/ICarService/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(ServiceReference2.Comanda comanda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOperation", ReplyAction="http://tempuri.org/ICarService/AddOperationResponse")]
        System.Threading.Tasks.Task AddOperationAsync(ServiceReference2.Operatie operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMecanic", ReplyAction="http://tempuri.org/ICarService/AddMecanicResponse")]
        System.Threading.Tasks.Task AddMecanicAsync(ServiceReference2.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddImage", ReplyAction="http://tempuri.org/ICarService/AddImageResponse")]
        System.Threading.Tasks.Task AddImageAsync(ServiceReference2.Imagine image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateClient", ReplyAction="http://tempuri.org/ICarService/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(ServiceReference2.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOrder", ReplyAction="http://tempuri.org/ICarService/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(ServiceReference2.Comanda order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOrderById", ReplyAction="http://tempuri.org/ICarService/FindOrderByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Comanda> FindOrderByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomerById", ReplyAction="http://tempuri.org/ICarService/FindCustomerByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Client> FindCustomerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteClient", ReplyAction="http://tempuri.org/ICarService/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsClient", ReplyAction="http://tempuri.org/ICarService/ExistsClientResponse")]
        System.Threading.Tasks.Task<bool> ExistsClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOrder", ReplyAction="http://tempuri.org/ICarService/DeleteOrderResponse")]
        System.Threading.Tasks.Task DeleteOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMaterialById", ReplyAction="http://tempuri.org/ICarService/FindMaterialByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Material> FindMaterialByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOperationById", ReplyAction="http://tempuri.org/ICarService/FindOperationByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Operatie> FindOperationByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMecanicById", ReplyAction="http://tempuri.org/ICarService/FindMecanicByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Mecanic> FindMecanicByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindImageById", ReplyAction="http://tempuri.org/ICarService/FindImageByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Imagine> FindImageByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrderDetails", ReplyAction="http://tempuri.org/ICarService/AddOrderDetailsResponse")]
        System.Threading.Tasks.Task AddOrderDetailsAsync(ServiceReference2.DetaliuComanda orderDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisById", ReplyAction="http://tempuri.org/ICarService/FindChassisByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Sasiu> FindChassisByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateChassis", ReplyAction="http://tempuri.org/ICarService/UpdateChassisResponse")]
        System.Threading.Tasks.Task UpdateChassisAsync(ServiceReference2.Sasiu chassis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteChassis", ReplyAction="http://tempuri.org/ICarService/DeleteChassisResponse")]
        System.Threading.Tasks.Task DeleteChassisAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMecanic", ReplyAction="http://tempuri.org/ICarService/UpdateMecanicResponse")]
        System.Threading.Tasks.Task UpdateMecanicAsync(ServiceReference2.Mecanic mecanic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMecanic", ReplyAction="http://tempuri.org/ICarService/DeleteMecanicResponse")]
        System.Threading.Tasks.Task DeleteMecanicAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateImage", ReplyAction="http://tempuri.org/ICarService/UpdateImageResponse")]
        System.Threading.Tasks.Task UpdateImageAsync(ServiceReference2.Imagine image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteImage", ReplyAction="http://tempuri.org/ICarService/DeleteImageResponse")]
        System.Threading.Tasks.Task DeleteImageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMaterial", ReplyAction="http://tempuri.org/ICarService/UpdateMaterialResponse")]
        System.Threading.Tasks.Task UpdateMaterialAsync(ServiceReference2.Material material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMaterial", ReplyAction="http://tempuri.org/ICarService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task DeleteMaterialAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOperation", ReplyAction="http://tempuri.org/ICarService/UpdateOperationResponse")]
        System.Threading.Tasks.Task UpdateOperationAsync(ServiceReference2.Operatie operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOperation", ReplyAction="http://tempuri.org/ICarService/DeleteOperationResponse")]
        System.Threading.Tasks.Task DeleteOperationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsCustomer", ReplyAction="http://tempuri.org/ICarService/ExistsCustomerResponse")]
        System.Threading.Tasks.Task<bool> ExistsCustomerAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ICarServiceChannel : ServiceReference2.ICarService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<ServiceReference2.ICarService>, ServiceReference2.ICarService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarServiceClient() : 
                base(CarServiceClient.GetDefaultBinding(), CarServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICarService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CarServiceClient.GetBindingForEndpoint(endpointConfiguration), CarServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Client> FindCustomerAsync(string nume, string prenume, string phoneNumber)
        {
            return base.Channel.FindCustomerAsync(nume, prenume, phoneNumber);
        }
        
        public System.Threading.Tasks.Task AddCustomerAsync(ServiceReference2.Client client)
        {
            return base.Channel.AddCustomerAsync(client);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Client[]> GetAllCustomersAsync()
        {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Threading.Tasks.Task AddChassisAsync(ServiceReference2.Sasiu sasiu)
        {
            return base.Channel.AddChassisAsync(sasiu);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Sasiu> FindChassisByCodeAsync(string chassisCode)
        {
            return base.Channel.FindChassisByCodeAsync(chassisCode);
        }
        
        public System.Threading.Tasks.Task AddAutoAsync(ServiceReference2.Auto auto)
        {
            return base.Channel.AddAutoAsync(auto);
        }
        
        public System.Threading.Tasks.Task AddMaterialAsync(ServiceReference2.Material material)
        {
            return base.Channel.AddMaterialAsync(material);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(ServiceReference2.Comanda comanda)
        {
            return base.Channel.AddOrderAsync(comanda);
        }
        
        public System.Threading.Tasks.Task AddOperationAsync(ServiceReference2.Operatie operation)
        {
            return base.Channel.AddOperationAsync(operation);
        }
        
        public System.Threading.Tasks.Task AddMecanicAsync(ServiceReference2.Mecanic mecanic)
        {
            return base.Channel.AddMecanicAsync(mecanic);
        }
        
        public System.Threading.Tasks.Task AddImageAsync(ServiceReference2.Imagine image)
        {
            return base.Channel.AddImageAsync(image);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(ServiceReference2.Client client)
        {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(ServiceReference2.Comanda order)
        {
            return base.Channel.UpdateOrderAsync(order);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Comanda> FindOrderByIdAsync(int id)
        {
            return base.Channel.FindOrderByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Client> FindCustomerByIdAsync(int id)
        {
            return base.Channel.FindCustomerByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(int id)
        {
            return base.Channel.DeleteClientAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsClientAsync(int id)
        {
            return base.Channel.ExistsClientAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(int id)
        {
            return base.Channel.DeleteOrderAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Material> FindMaterialByIdAsync(int id)
        {
            return base.Channel.FindMaterialByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Operatie> FindOperationByIdAsync(int id)
        {
            return base.Channel.FindOperationByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Mecanic> FindMecanicByIdAsync(int id)
        {
            return base.Channel.FindMecanicByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Imagine> FindImageByIdAsync(int id)
        {
            return base.Channel.FindImageByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task AddOrderDetailsAsync(ServiceReference2.DetaliuComanda orderDetails)
        {
            return base.Channel.AddOrderDetailsAsync(orderDetails);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Sasiu> FindChassisByIdAsync(int id)
        {
            return base.Channel.FindChassisByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateChassisAsync(ServiceReference2.Sasiu chassis)
        {
            return base.Channel.UpdateChassisAsync(chassis);
        }
        
        public System.Threading.Tasks.Task DeleteChassisAsync(int id)
        {
            return base.Channel.DeleteChassisAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateMecanicAsync(ServiceReference2.Mecanic mecanic)
        {
            return base.Channel.UpdateMecanicAsync(mecanic);
        }
        
        public System.Threading.Tasks.Task DeleteMecanicAsync(int id)
        {
            return base.Channel.DeleteMecanicAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateImageAsync(ServiceReference2.Imagine image)
        {
            return base.Channel.UpdateImageAsync(image);
        }
        
        public System.Threading.Tasks.Task DeleteImageAsync(int id)
        {
            return base.Channel.DeleteImageAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateMaterialAsync(ServiceReference2.Material material)
        {
            return base.Channel.UpdateMaterialAsync(material);
        }
        
        public System.Threading.Tasks.Task DeleteMaterialAsync(int id)
        {
            return base.Channel.DeleteMaterialAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateOperationAsync(ServiceReference2.Operatie operation)
        {
            return base.Channel.UpdateOperationAsync(operation);
        }
        
        public System.Threading.Tasks.Task DeleteOperationAsync(int id)
        {
            return base.Channel.DeleteOperationAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsCustomerAsync(string email)
        {
            return base.Channel.ExistsCustomerAsync(email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICarService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICarService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/ServiceWCF/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CarServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICarService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CarServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICarService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICarService,
        }
    }
}
