//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiPhoto
    {
        public int Id { get; set; }
        public int Title { get; set; }
        public System.DateTime Date { get; set; }
        public string People { get; set; }
        public string Location { get; set; }
        public string Event { get; set; }
        public string Description { get; set; }
    
        public virtual Photos Photo { get; set; }
    }
}
