//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int Id { get; set; }
        public System.DateTime DateMemory { get; set; }
        public byte[] PathFoto { get; set; }
    
        public virtual DetaliiPhoto DetaliiPhoto { get; set; }
        public virtual Search Search { get; set; }
    }
}
